# Cloud Build configuration for Trading Agent
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trading-agent:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/trading-agent:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'cloud_run_trading_agent'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/trading-agent:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/trading-agent:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'trading-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/trading-agent:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,ANTHROPIC_API_KEY=$_ANTHROPIC_API_KEY'

images:
  - 'gcr.io/$PROJECT_ID/trading-agent:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/trading-agent:latest'

timeout: '1200s'

substitutions:
  _ANTHROPIC_API_KEY: ''
